export const INIT_FIREBASE_REQUEST = 'INIT_FIREBASE_REQUEST'
export const INIT_FIREBASE_ABORT = 'INIT_FIREBASE_ABORT'
export const INIT_FIREBASE_SUCCESS = 'INIT_FIREBASE_SUCCESS'
export const INIT_FIREBASE_FAIL = 'INIT_FIREBASE_FAIL'